### ISSUE TITLE
long_reads_citation.txt

### ISSUE THREAD

**Issue by davidmadariaga** [pablorr24/metagenomics_snakemake#1]
Hi!!!, hope you are doing great!. The program it's giving me this error, do you know what could be the reason??
Im attaching a screenshot. Feel free, please, to ask me whatever you want.

![image](https://github.com/pablorr24/metagenomics_snakemake/assets/25496906/6615269e-ea3b-4868-a984-ce7f969733c9)

(snakemake_meta) [mdavid@n003 metagenomics_snakemake]$ snakemake -s Snakefile_long_reads_full_workflow --cores all
Building DAG of jobs...
MissingInputException in rule citation in file /home/bioren/mdavid/metagenomics_snakemake/rules/long_reads/rule_citation_long.snake, line 2:
Missing input files for rule citation:
    output: /home/bioren/mdavid/UA/FONDECYTKATTIA/microbiomeanalyst_final/A/pruebasnakemake/output/long_reads/long_read_res04-Jul-2024-18/long_reads_citation.txt
    wildcards: wd=/home/bioren/mdavid/UA/FONDECYTKATTIA/microbiomeanalyst_final/A/pruebasnakemake, rs=long_read_res04-Jul-2024-18
    affected files:
        /home/bioren/mdavid/UA/FONDECYTKATTIA/microbiomeanalyst_final/A/pruebasnakemake/citations/long_reads_citation.txt

Greetings from Chile, South America!!

**Comment by pablorr24** [comment]
Hi David,
Is there a file called long_reads_citation.txt in the citations folder? It should have been included when you installed the repository. The error is telling you that this file wasn't found.

Feel free to reach out for any other questions.

Note: edited to refer to the right file name (typo)

**Comment by davidmadariaga** [comment]
Thanks for answering!, there's not!

**Comment by davidmadariaga** [comment]
there are only these ones: fastqc_citation.txt  long_reads_citation.txt  nanoplot_citation.txt  post_analysis_citation.txt  short_reads_citation.txt

**Comment by davidmadariaga** [comment]
my bad, i did not see it, what could be happening then?

**Comment by pablorr24** [comment]
I mistyped the file name earlier, I meant long_reads_citation.txt, so that's not the problem. 

I think I know now what's the issue. You should edit your config file (config_templates/config_long_reads_full_workflow.yaml) and in the working_directory parameter you should set it to your main Snakemake Metagenomics folder (where you're running the main command). I believe it's this:
/home/bioren/mdavid/UA/FONDECYTKATTIA/microbiomeanalyst_final/A/pruebasnakemake

You should also set up the other parameters if you haven't done so.

Any questions you can reach me directly as well.

**Comment by davidmadariaga** [comment]
ok, thanks!! i'll try the suggestions, thanks thanks

**Comment by davidmadariaga** [comment]
hi again!, now it's giving me this, any ideas why?
feel free to answer whenever you can, thanks in advance!!

(snakemake_meta) [mdavid@mapudungun-frontend metagenomics_snakemake]$ snakemake -s Snakefile_long_reads_full_workflow --cores all
Building DAG of jobs...
File path /home/bioren/mdavid/metagenomics_snakemake//output/long_reads/long_read_res04-Jul-2024-20/long_config_04-Jul-2024-20.yaml contains double '/'. This is likely unintended. It can also lead to inconsistent results of the file-matching approach used by Snakemake.
File path /home/bioren/mdavid/metagenomics_snakemake//output/long_reads/long_read_res04-Jul-2024-20/kraken_report_paths.txt contains double '/'. This is likely unintended. It can also lead to inconsistent results of the file-matching approach used by Snakemake.
File path /home/bioren/mdavid/metagenomics_snakemake//output/long_reads/long_read_res04-Jul-2024-20/otu_table_G.csv contains double '/'. This is likely unintended. It can also lead to inconsistent results of the file-matching approach used by Snakemake.
File path /home/bioren/mdavid/metagenomics_snakemake//output/long_reads/long_read_res04-Jul-2024-20/long_reads_citation.txt contains double '/'. This is likely unintended. It can also lead to inconsistent results of the file-matching approach used by Snakemake.
File path /home/bioren/mdavid/metagenomics_snakemake//output/long_reads/long_read_res04-Jul-2024-20/long_config_04-Jul-2024-20.yaml contains double '/'. This is likely unintended. It can also lead to inconsistent results of the file-matching approach used by Snakemake.
File path /home/bioren/mdavid/metagenomics_snakemake//output/long_reads/long_read_res04-Jul-2024-20/kraken_report_paths.txt contains double '/'. This is likely unintended. It can also lead to inconsistent results of the file-matching approach used by Snakemake.
File path /home/bioren/mdavid/metagenomics_snakemake//output/long_reads/long_read_res04-Jul-2024-20/kraken_report_paths.txt contains double '/'. This is likely unintended. It can also lead to inconsistent results of the file-matching approach used by Snakemake.
File path /home/bioren/mdavid/metagenomics_snakemake//output/long_reads/long_read_res04-Jul-2024-20/otu_table_G.csv contains double '/'. This is likely unintended. It can also lead to inconsistent results of the file-matching approach used by Snakemake.
File path /home/bioren/mdavid/metagenomics_snakemake//citations/long_reads_citation.txt contains double '/'. This is likely unintended. It can also lead to inconsistent results of the file-matching approach used by Snakemake.
File path /home/bioren/mdavid/metagenomics_snakemake//output/long_reads/long_read_res04-Jul-2024-20/long_reads_citation.txt contains double '/'. This is likely unintended. It can also lead to inconsistent results of the file-matching approach used by Snakemake.
Using shell: /usr/bin/bash
Provided cores: 2
Rules claiming more threads will be scaled down.
Job stats:
job                      count
---------------------  -------
all                          1
citation                     1
create_otu_table_long        1
generate_config_file         1
post_check_rule_long         1
total                        5

Select jobs to execute...

[Thu Jul  4 20:53:26 2024]
rule generate_config_file:
    output: /home/bioren/mdavid/metagenomics_snakemake//output/long_reads/long_read_res04-Jul-2024-20/long_config_04-Jul-2024-20.yaml
    jobid: 1
    reason: Missing output files: /home/bioren/mdavid/metagenomics_snakemake//output/long_reads/long_read_res04-Jul-2024-20/long_config_04-Jul-2024-20.yaml
    wildcards: wd=/home/bioren/mdavid/metagenomics_snakemake/, rs=long_read_res04-Jul-2024-20, ts=04-Jul-2024-20
    resources: tmpdir=/tmp

[Thu Jul  4 20:53:26 2024]
rule post_check_rule_long:
    output: /home/bioren/mdavid/metagenomics_snakemake//output/long_reads/long_read_res04-Jul-2024-20/kraken_report_paths.txt
    jobid: 2
    reason: Missing output files: /home/bioren/mdavid/metagenomics_snakemake//output/long_reads/long_read_res04-Jul-2024-20/kraken_report_paths.txt
    wildcards: wd=/home/bioren/mdavid/metagenomics_snakemake/, rs=long_read_res04-Jul-2024-20
    resources: tmpdir=/tmp

Building DAG of jobs...
File path /home/bioren/mdavid/metagenomics_snakemake//output/long_reads/long_read_res04-Jul-2024-20/long_config_04-Jul-2024-20.yaml contains double '/'. This is likely unintended. It can also lead to inconsistent results of the file-matching approach used by Snakemake.
Building DAG of jobs...
File path /home/bioren/mdavid/metagenomics_snakemake//output/long_reads/long_read_res04-Jul-2024-20/kraken_report_paths.txt contains double '/'. This is likely unintended. It can also lead to inconsistent results of the file-matching approach used by Snakemake.
Using shell: /usr/bin/bash
Provided cores: 2
Using shell: /usr/bin/bash
Rules claiming more threads will be scaled down.
Provided cores: 2
Select jobs to execute...
Rules claiming more threads will be scaled down.
Select jobs to execute...
Generated config file: /home/bioren/mdavid/metagenomics_snakemake//output/long_reads/long_read_res04-Jul-2024-20/long_config_04-Jul-2024-20.yaml
[Thu Jul  4 20:53:28 2024]
Finished job 1.
1 of 5 steps (20%) done
Select jobs to execute...

[Thu Jul  4 20:53:28 2024]
rule citation:
    input: /home/bioren/mdavid/metagenomics_snakemake//citations/long_reads_citation.txt
    output: /home/bioren/mdavid/metagenomics_snakemake//output/long_reads/long_read_res04-Jul-2024-20/long_reads_citation.txt
    jobid: 4
    reason: Missing output files: /home/bioren/mdavid/metagenomics_snakemake//output/long_reads/long_read_res04-Jul-2024-20/long_reads_citation.txt
    wildcards: wd=/home/bioren/mdavid/metagenomics_snakemake/, rs=long_read_res04-Jul-2024-20
    resources: tmpdir=/tmp

[Thu Jul  4 20:53:28 2024]
Finished job 2.
2 of 5 steps (40%) done
Select jobs to execute...

[Thu Jul  4 20:53:28 2024]
rule create_otu_table_long:
    input: /home/bioren/mdavid/metagenomics_snakemake//output/long_reads/long_read_res04-Jul-2024-20/kraken_report_paths.txt
    output: /home/bioren/mdavid/metagenomics_snakemake//output/long_reads/long_read_res04-Jul-2024-20/otu_table_G.csv
    jobid: 3
    reason: Missing output files: /home/bioren/mdavid/metagenomics_snakemake//output/long_reads/long_read_res04-Jul-2024-20/otu_table_G.csv; Input files updated by another job: /home/bioren/mdavid/metagenomics_snakemake//output/long_reads/long_read_res04-Jul-2024-20/kraken_report_paths.txt
    wildcards: wd=/home/bioren/mdavid/metagenomics_snakemake/, rs=long_read_res04-Jul-2024-20, lv=G
    resources: tmpdir=/tmp

Creating OTU table
[Thu Jul  4 20:53:28 2024]
Finished job 4.
3 of 5 steps (60%) done
Traceback (most recent call last):
  File "/home/bioren/mdavid/metagenomics_snakemake/scripts/kraken2OTU.py", line 117, in <module>
    file_dict = read_in_files(args.reportpathsfile)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bioren/mdavid/metagenomics_snakemake/scripts/kraken2OTU.py", line 64, in read_in_files
    raise AssertionError("No report files found in the provided file!")
AssertionError: No report files found in the provided file!
[Thu Jul  4 20:53:28 2024]
Error in rule create_otu_table_long:
    jobid: 3
    input: /home/bioren/mdavid/metagenomics_snakemake//output/long_reads/long_read_res04-Jul-2024-20/kraken_report_paths.txt
    output: /home/bioren/mdavid/metagenomics_snakemake//output/long_reads/long_read_res04-Jul-2024-20/otu_table_G.csv
    shell:
        
        echo "Creating OTU table"
        python3 scripts/kraken2OTU.py --reportpathsfile /home/bioren/mdavid/metagenomics_snakemake//output/long_reads/long_read_res04-Jul-2024-20/kraken_report_paths.txt --level G --outputfolder /home/bioren/mdavid/metagenomics_snakemake//output/long_reads/long_read_res04-Jul-2024-20/
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-07-04T205320.478090.snakemake.log

**Comment by pablorr24** [comment]
Just remove the last '/' from your working directory path in the config file. But that's a good observation, I'll make some changes to make this clear. I think your analysis should work soon :)

**Comment by davidmadariaga** [comment]
Hi, i changed the / at the end but it seems that im getting the same error, this is what i got:

(snakemake_meta) [mdavid@n003 metagenomics_snakemake]$ snakemake -s Snakefile_long_reads_full_workflow --cores 20
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 20
Rules claiming more threads will be scaled down.
Job stats:
job                      count
---------------------  -------
all                          1
create_otu_table_long        1
total                        2

Select jobs to execute...

[Fri Jul  5 16:37:38 2024]
rule create_otu_table_long:
    input: /home/bioren/mdavid/metagenomics_snakemake/output/long_reads/long_read_res05-Jul-2024-16/kraken_report_paths.txt
    output: /home/bioren/mdavid/metagenomics_snakemake/output/long_reads/long_read_res05-Jul-2024-16/otu_table_G.csv
    jobid: 3
    reason: Missing output files: /home/bioren/mdavid/metagenomics_snakemake/output/long_reads/long_read_res05-Jul-2024-16/otu_table_G.csv
    wildcards: wd=/home/bioren/mdavid/metagenomics_snakemake, rs=long_read_res05-Jul-2024-16, lv=G
    resources: tmpdir=/tmp

Creating OTU table
Traceback (most recent call last):
  File "/home/bioren/mdavid/metagenomics_snakemake/scripts/kraken2OTU.py", line 117, in <module>
    file_dict = read_in_files(args.reportpathsfile)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bioren/mdavid/metagenomics_snakemake/scripts/kraken2OTU.py", line 64, in read_in_files
    raise AssertionError("No report files found in the provided file!")
AssertionError: No report files found in the provided file!
[Fri Jul  5 16:37:38 2024]
Error in rule create_otu_table_long:
    jobid: 3
    input: /home/bioren/mdavid/metagenomics_snakemake/output/long_reads/long_read_res05-Jul-2024-16/kraken_report_paths.txt
    output: /home/bioren/mdavid/metagenomics_snakemake/output/long_reads/long_read_res05-Jul-2024-16/otu_table_G.csv
    shell:
        
        echo "Creating OTU table"
        python3 scripts/kraken2OTU.py --reportpathsfile /home/bioren/mdavid/metagenomics_snakemake/output/long_reads/long_read_res05-Jul-2024-16/kraken_report_paths.txt --level G --outputfolder /home/bioren/mdavid/metagenomics_snakemake/output/long_reads/long_read_res05-Jul-2024-16/
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-07-05T163736.845480.snakemake.log


btw, this is my config file:
(snakemake_meta) [mdavid@n003 config_templates]$ cat config_long_reads_full_workflow.yaml 
#Run the long-reads full workflow by configuring these file and typing in the terminal
#snakemake -s Snakefile_long_reads_full_workflow --cores all 
working_directory: /home/bioren/mdavid/metagenomics_snakemake

sample_path: /home/bioren/mdavid/UA/FONDECYTKATTIA/microbiomeanalyst_final/A/pruebasnakemake


database_path: /home/bioren/mdavid/centrifuge_last/centrifuge
prefix: silva_16S_index

nanofilt_parameters:
  LENGTH: 1000 #default=0
  QUALITY: 10 #default=0
#Optional Parameteres
  MAXLENGTH: 1900
  MINGC: 0
  MAXGC: 1
  HEADCROP: 0
  TAILCROP: 0
  
#Centrifuge
centrifuge_parameters:
  max_hits: 5 #default=5
  
#Diversity
alpha_diversity: "all" #options: all, Shannon, Simpson, Fischer, BP (Berger-Parkers) 

#Taxonomic Level
otu_table_level: G
 
thanks in advance, feel free to answer whenever you can.

Greetings!
